/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import static Pantallas.Clientes.tbClientes;
import clases.colorCelda;
import clases.conexionS;
import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rica_
 */
public class EstadoOS extends javax.swing.JInternalFrame {

    Connection conexion = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form EstadoOS
     */
    public EstadoOS() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        conexion = conexionS.conn();

    }

    private void colorear() {
        colorCelda color = new colorCelda(11);
        jTableGeneral.getColumnModel().getColumn(11).setCellRenderer(color);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pestañas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGeneral = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableProceso = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTerminadas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCanceladas = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1320, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/estado.png"))); // NOI18N
        jLabel1.setText("Estado Ordenes de Servicio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(495, 495, 495))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Pestañas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PestañasStateChanged(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGeneral = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableGeneral.setFont(new java.awt.Font("Roboto", 0, 14));
        jTableGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGeneral.setFocusable(false);
        jTableGeneral.setRowHeight(30);
        jTableGeneral.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableGeneral);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 630));

        Pestañas.addTab("General", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGeneral = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableProceso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProceso.setFocusable(false);
        jTableProceso.setRowHeight(30);
        jTableProceso.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTableProceso);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 630));

        jButton1.setText("Editar");
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Pestañas.addTab("En proceso", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGeneral = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableTerminadas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableTerminadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTerminadas.setFocusable(false);
        jTableTerminadas.setRowHeight(30);
        jTableTerminadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableTerminadas);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 630));

        jButton2.setText("Ver informe");
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton3.setText("Imprimir informe");
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        Pestañas.addTab("Terminadas", jPanel6);

        jPanel7.setFont(new java.awt.Font("Rage Italic", 0, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGeneral = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableCanceladas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableCanceladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCanceladas.setFocusable(false);
        jTableCanceladas.setRowHeight(30);
        jTableCanceladas.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTableCanceladas);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 630));

        Pestañas.addTab("Canceladas", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(Pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 1287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PestañasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PestañasStateChanged
        // TODO add your handling code here:

        if (Pestañas.getTitleAt(Pestañas.getSelectedIndex()).equals("General")) {

            conexion = conexionS.conn();
            DefaultTableModel tgeneral = new DefaultTableModel();
            tgeneral.addColumn("NumeroOS");
            tgeneral.addColumn("Fecha Ingreso");
            tgeneral.addColumn("Fecha salida");
            tgeneral.addColumn("Emitida por");
            tgeneral.addColumn("Tecnico Asignado");
            tgeneral.addColumn("Nombre Cliente");
            tgeneral.addColumn("Direccion Cliente");
            tgeneral.addColumn("Telefono");
            tgeneral.addColumn("Correo Cliente");
            tgeneral.addColumn("Tipo de dispositivo");
            tgeneral.addColumn("Reporte cliente");
            tgeneral.addColumn("Estatus");
            tgeneral.addColumn("Estatus Pago");
            tgeneral.addColumn("Total");
            jTableGeneral.setModel(tgeneral);

            String[] datos = new String[14];

            String sql = "select * from os";
            try {

                Statement leer = conexion.createStatement();
                rs = leer.executeQuery(sql);

                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getString(4);
                    datos[4] = rs.getString(5);
                    datos[5] = rs.getString(6);
                    datos[6] = rs.getString(7);
                    datos[7] = rs.getString(8);
                    datos[8] = rs.getString(9);
                    datos[9] = rs.getString(10);
                    datos[10] = rs.getString(11);
                    datos[11] = rs.getString(18);
                    datos[12] = rs.getString(19);
                    datos[13] = rs.getString(20);
                    tgeneral.addRow(datos);
                    colorear();
                    

                }
                jTableGeneral.setModel(tgeneral);
                conexion.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else if (Pestañas.getTitleAt(Pestañas.getSelectedIndex()).equals("En proceso")) {

            conexion = conexionS.conn();
            DefaultTableModel tProceso = new DefaultTableModel();
            tProceso.addColumn("NumeroOS");
            tProceso.addColumn("Fecha Ingreso");
            tProceso.addColumn("Fecha salida");
            tProceso.addColumn("Emitida por");
            tProceso.addColumn("Tecnico Asignado");
            tProceso.addColumn("Nombre Cliente");
            tProceso.addColumn("Direccion Cliente");
            tProceso.addColumn("Telefono");
            tProceso.addColumn("Correo Cliente");
            tProceso.addColumn("Tipo de dispositivo");
            tProceso.addColumn("Reporte cliente");
            tProceso.addColumn("Estatus");
            tProceso.addColumn("Estatus Pago");
            tProceso.addColumn("Total");
            jTableProceso.setModel(tProceso);

            String[] datos = new String[14];

            String sql = "select * from os where Estatus= 'En proceso'";
            try {

                Statement leer = conexion.createStatement();
                rs = leer.executeQuery(sql);

                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getString(4);
                    datos[4] = rs.getString(5);
                    datos[5] = rs.getString(6);
                    datos[6] = rs.getString(7);
                    datos[7] = rs.getString(8);
                    datos[8] = rs.getString(9);
                    datos[9] = rs.getString(10);
                    datos[10] = rs.getString(11);
                    datos[11] = rs.getString(18);
                    datos[12] = rs.getString(19);
                    datos[13] = rs.getString(20);
                    tProceso.addRow(datos);
                    

                }
                jTableGeneral.setModel(tProceso);
                conexion.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_PestañasStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Pestañas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableCanceladas;
    private javax.swing.JTable jTableGeneral;
    private javax.swing.JTable jTableProceso;
    private javax.swing.JTable jTableTerminadas;
    // End of variables declaration//GEN-END:variables
}
