/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import clases.conexionS;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import clases.*;
import java.util.Date;
import java.awt.Color;

/**
 *
 * @author rica_
 */
public class Os extends javax.swing.JInternalFrame {

    Connection conexion = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel tServicios = new DefaultTableModel();

    /**
     * Creates new form Os
     */
    public Os() {
        initComponents();
        Contraseña.setEnabled(false);
        txtAccerosorios.setEnabled(false);

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        conexion = conexionS.conn();
        txtAccerosorios.setLineWrap(true);
        txtAccerosorios.setWrapStyleWord(true);
        jTxtObservaciones.setLineWrap(true);
        jTxtObservaciones.setWrapStyleWord(true);

        CambiarEstatus();
        cargarCombobox();
        MostrarServicios();
    }

    private void cargarCombobox() {

        cbTecnicos cb = new cbTecnicos();
        cbTecnico.setModel(cb.getvalues());

        cbServicios cb2 = new cbServicios();
        cbServicios.setModel(cb2.getvalues());
    }

    private void MostrarServicios() {

        tServicios.addColumn("Servicio");
        tServicios.addColumn("Costo");
        jTableServicios.setModel(tServicios);

    }

    private void SumarDatos() {

        int aux = jTableServicios.getRowCount();
        int suma = 0;

        for (int i = 0; i < aux; i++) {
            suma += Integer.parseInt(jTableServicios.getValueAt(i, 1).toString());

        }
        Total.setText(String.valueOf(suma));
    }

    private void CambiarEstatus() {

        if (Estatus.getText() == "Asignado") {
            Estatus.setBackground(new Color(36, 113, 163));

        } else if (Estatus.getText() == "Sin Asignar") {
            Estatus.setBackground(Color.red);
        }

        if (Pago.getText() == "No Pagado") {
            Pago.setBackground(Color.red);
        } else if (Pago.getText() == "Pagado") {
            Pago.setBackground(new Color(0, 184, 33));

        } else if (Pago.getText() == "Estatus Pago") {
            Pago.setBackground(Color.GRAY);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DatosGenereales = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        numOS = new javax.swing.JTextField();
        EmitidaPor = new javax.swing.JTextField();
        cbTecnico = new javax.swing.JComboBox<>();
        Salida = new com.toedter.calendar.JDateChooser();
        ingreso1 = new com.toedter.calendar.JDateChooser();
        DatosClientes = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        AgregarCliente = new javax.swing.JButton();
        SeleccionarCliente = new javax.swing.JButton();
        DatosEquipo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Marca = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        Accesorios = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Si = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAccerosorios = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JTextField();
        Observaciones = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtObservaciones = new javax.swing.JTextArea();
        ReporteCliente = new javax.swing.JPanel();
        num = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtReporte = new javax.swing.JTextArea();
        Servicios = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        cbServicios = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Costo = new javax.swing.JFormattedTextField();
        Eliminar = new javax.swing.JButton();
        Importe = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Estatus = new javax.swing.JLabel();
        Pago = new javax.swing.JLabel();
        Total = new javax.swing.JFormattedTextField();
        cbPago = new javax.swing.JComboBox<>();
        NuevaOs = new javax.swing.JButton();
        GuardarOs = new javax.swing.JButton();
        EditarOs = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1326, 880));
        setPreferredSize(new java.awt.Dimension(1326, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 880));

        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_bill_32px.png"))); // NOI18N
        jLabel1.setText("Ordenes de Servicio");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);
        Banner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 40));

        DatosGenereales.setBackground(new java.awt.Color(153, 153, 153));
        DatosGenereales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosGenereales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(80, 34, 34));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATOS GENERALES");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        DatosGenereales.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        label1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label1.setText("N° OS");
        DatosGenereales.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label2.setText("Fecha de ingreso");
        DatosGenereales.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label4.setText("Fecha de entrega");
        DatosGenereales.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        label5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label5.setText("Emitida por");
        DatosGenereales.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label6.setText("Tecnico asignado");
        DatosGenereales.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        numOS.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        numOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOSActionPerformed(evt);
            }
        });
        DatosGenereales.add(numOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        EmitidaPor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        DatosGenereales.add(EmitidaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, -1));

        cbTecnico.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cbTecnico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTecnicoItemStateChanged(evt);
            }
        });
        cbTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTecnicoActionPerformed(evt);
            }
        });
        DatosGenereales.add(cbTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        Salida.setDateFormatString("d/ MM/y");
        DatosGenereales.add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        ingreso1.setDateFormatString("d/ MM/y");
        DatosGenereales.add(ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        DatosClientes.setBackground(new java.awt.Color(153, 153, 153));
        DatosClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(80, 34, 34));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DATOS DE CLIENTE");
        jPanel21.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        DatosClientes.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel22.setBackground(new java.awt.Color(153, 153, 153));
        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(80, 34, 34));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DATOS DE CLIENTE");
        jPanel23.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        DatosClientes.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 350, 150));

        label7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label7.setText("Correo");
        DatosClientes.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label8.setText("Nombre");
        DatosClientes.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label9.setText("Dirección");
        DatosClientes.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label10.setText("Teléfono");
        DatosClientes.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        DatosClientes.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        Direccion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        DatosClientes.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, -1));

        Telefono.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        DatosClientes.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, -1));

        Correo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        DatosClientes.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, -1));

        AgregarCliente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        AgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_24px_1.png"))); // NOI18N
        AgregarCliente.setText("Agregar");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        DatosClientes.add(AgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        SeleccionarCliente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        SeleccionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_checklist_24px.png"))); // NOI18N
        SeleccionarCliente.setText("Seleccionar");
        SeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarClienteActionPerformed(evt);
            }
        });
        DatosClientes.add(SeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 30));

        DatosEquipo.setBackground(new java.awt.Color(153, 153, 153));
        DatosEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosEquipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(80, 34, 34));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATOS DEL EQUIPO");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 30));

        DatosEquipo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        label13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label13.setText("Tipo de Dispositivo");
        DatosEquipo.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label12.setText("Marca");
        DatosEquipo.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label14.setText("Modelo");
        DatosEquipo.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        label11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label11.setText("N° Serie");
        DatosEquipo.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ------------------------Selecciona un Dispositivo------------------------", "Laptop", "Proyector", "Impresora", "PC", "Tablet", "Monitor", "Teclado", "Plotter", "No Breaks" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        DatosEquipo.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 310, -1));
        DatosEquipo.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 310, -1));
        DatosEquipo.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, -1));

        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        DatosEquipo.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, -1));

        Accesorios.setBackground(new java.awt.Color(153, 153, 153));
        Accesorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Accesorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(80, 34, 34));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Accesorios");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 30));

        buttonGroup1.add(Si);
        Si.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Si.setForeground(new java.awt.Color(255, 255, 255));
        Si.setText("SI");
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        jPanel15.add(Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        buttonGroup1.add(No);
        No.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        No.setForeground(new java.awt.Color(255, 255, 255));
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        jPanel15.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 30));

        Accesorios.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel19.setBackground(new java.awt.Color(153, 153, 153));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(80, 34, 34));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATOS DE CLIENTE");
        jPanel20.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        Accesorios.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 350, 150));

        txtAccerosorios.setColumns(20);
        txtAccerosorios.setRows(5);
        jScrollPane2.setViewportView(txtAccerosorios);

        Accesorios.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Accesorios");
        Accesorios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        Accesorios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        Accesorios.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        Observaciones.setBackground(new java.awt.Color(153, 153, 153));
        Observaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Observaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(80, 34, 34));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OBSERVACIONES");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 30));

        Observaciones.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 30));

        jTxtObservaciones.setColumns(20);
        jTxtObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTxtObservaciones);

        Observaciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 890, 110));

        ReporteCliente.setBackground(new java.awt.Color(153, 153, 153));
        ReporteCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ReporteCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num.setBackground(new java.awt.Color(80, 34, 34));
        num.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        num.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REPORTE CLIENTE");
        num.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 30));

        ReporteCliente.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jTxtReporte.setColumns(20);
        jTxtReporte.setRows(5);
        jScrollPane3.setViewportView(jTxtReporte);

        ReporteCliente.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 110));

        Servicios.setBackground(new java.awt.Color(153, 153, 153));
        Servicios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Servicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(80, 34, 34));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SERVICIOS");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 30));

        Servicios.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        jTableServicios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableServicios);

        Servicios.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 910, 110));

        cbServicios.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cbServicios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbServiciosItemStateChanged(evt);
            }
        });
        cbServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServiciosActionPerformed(evt);
            }
        });
        Servicios.add(cbServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Costo    $");
        Servicios.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 80, 20));

        Agregar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_24px_1.png"))); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        Servicios.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, 20));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Seleccionar Servicio a realizar ");
        Servicios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Costo.setEditable(false);
        Costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###.00"))));
        Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoActionPerformed(evt);
            }
        });
        Servicios.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 150, 30));

        Eliminar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_cancel_24px.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Servicios.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 110, 20));

        Importe.setBackground(new java.awt.Color(153, 153, 153));
        Importe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Importe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(80, 34, 34));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IMPORTE");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 30));

        Importe.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("Total");
        Importe.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Estatus.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Estatus.setForeground(new java.awt.Color(0, 0, 0));
        Estatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estatus.setText("Sin Asignar");
        Estatus.setOpaque(true);
        Importe.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 40));

        Pago.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Pago.setForeground(new java.awt.Color(0, 0, 0));
        Pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pago.setText("Estatus Pago");
        Pago.setOpaque(true);
        Importe.add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 40));

        Total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.setEnabled(false);
        Importe.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 210, -1));

        cbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus Pago", "Pagado", "No Pagado" }));
        cbPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPagoItemStateChanged(evt);
            }
        });
        Importe.add(cbPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

        NuevaOs.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        NuevaOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_24px_1.png"))); // NOI18N
        NuevaOs.setText("Nuevo");
        NuevaOs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NuevaOs.setPreferredSize(new java.awt.Dimension(75, 23));
        NuevaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaOsActionPerformed(evt);
            }
        });

        GuardarOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_save_24px.png"))); // NOI18N
        GuardarOs.setText("Guardar ");
        GuardarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOsActionPerformed(evt);
            }
        });

        EditarOs.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        EditarOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_edit_24px.png"))); // NOI18N
        EditarOs.setText("Editar");
        EditarOs.setMaximumSize(new java.awt.Dimension(75, 23));
        EditarOs.setMinimumSize(new java.awt.Dimension(75, 23));
        EditarOs.setPreferredSize(new java.awt.Dimension(75, 23));
        EditarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarOsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NuevaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(EditarOs, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DatosGenereales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarOs, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarOs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NuevaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatosGenereales, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(ReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(GuardarOs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        setBounds(0, 0, 1345, 880);
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void numOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOSActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void GuardarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOsActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_GuardarOsActionPerformed

    private void EditarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarOsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarOsActionPerformed

    private void cbTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTecnicoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloActionPerformed

    private void cbServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServiciosActionPerformed

    private void CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoActionPerformed

    private void NuevaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaOsActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_NuevaOsActionPerformed

    private void cbServiciosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbServiciosItemStateChanged
        // TODO add your handling code here:
        String sql = "SELECT precio FROM catalogoprecios where descripcion=?";
        try {
            pst = conexion.prepareStatement(sql);
            pst.setString(1, cbServicios.getSelectedItem().toString());
            rs = pst.executeQuery();

            if (rs.next()) {

                Costo.setText(rs.getString(1));

            } else {
                Costo.setText("");
            }

        } catch (SQLException e) {
        }


    }//GEN-LAST:event_cbServiciosItemStateChanged

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:

        String Dato[] = new String[2];
        Dato[0] = cbServicios.getSelectedItem().toString();
        Dato[1] = Costo.getText();
        if (Dato[0] == "   ------Selecciona Servicio------" && Dato[1].isEmpty()) {

            JOptionPane.showMessageDialog(null, "Agregue un servicio");

        } else {
            tServicios.addRow(Dato);

        }
        SumarDatos();


    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int FilaSelect = jTableServicios.getSelectedRow();

        if (FilaSelect >= 0) {
            tServicios.removeRow(FilaSelect);
        }
        SumarDatos();
    }//GEN-LAST:event_EliminarActionPerformed

    private void cbTecnicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTecnicoItemStateChanged
        // TODO add your handling code here:

        if (cbTecnico.getSelectedItem().toString() == "------Selecciona tecnico------") {

            Estatus.setText("Sin Asignar");

        } else {
            Estatus.setText("Asignado");
        }

        CambiarEstatus();
    }//GEN-LAST:event_cbTecnicoItemStateChanged

    private void cbPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPagoItemStateChanged
        // TODO add your handling code here:

        Pago.setText((cbPago.getSelectedItem().toString()));
        CambiarEstatus();
    }//GEN-LAST:event_cbPagoItemStateChanged

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:

        String sql = "Select nombre from clientes where nombre=?";

        try {
            pst = conexion.prepareStatement(sql);
            pst.setString(1, Nombre.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "El cliente "
                        + rs.getString(1) + " Ya esta registrado");
            } else {

                sql = ("insert into clientes(nombre,direccion,telefono,correo)"
                        + "values(?,?,?,?)");
                try {
                    if (Nombre.getText().isEmpty()
                            || Direccion.getText().isEmpty()
                            || Telefono.getText().isEmpty()
                            || Correo.getText().isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Campos obligatorios vacios");
                    } else {

                        pst = conexion.prepareStatement(sql);
                        pst.setString(1, Nombre.getText());
                        pst.setString(2, Correo.getText());
                        pst.setString(3, Direccion.getText());
                        pst.setString(4, Telefono.getText());
                        pst.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Cliente agregado exitosamente");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void SeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarClienteActionPerformed
        // TODO add your handling code here:

        TableClient tableclient = new TableClient();
        tableclient.setVisible(true);
    }//GEN-LAST:event_SeleccionarClienteActionPerformed

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:

        if (Si.isSelected()) {

            Contraseña.setEnabled(true);
            txtAccerosorios.setEnabled(true);

        }
    }//GEN-LAST:event_SiActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        if (No.isSelected()) {

            Contraseña.setEnabled(false);
            txtAccerosorios.setEnabled(false);
            
            Contraseña.setText("");
            txtAccerosorios.setText("");
            
           

        }
    }//GEN-LAST:event_NoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accesorios;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JPanel Banner;
    private javax.swing.JTextField Contraseña;
    public static javax.swing.JTextField Correo;
    private javax.swing.JFormattedTextField Costo;
    private javax.swing.JPanel DatosClientes;
    private javax.swing.JPanel DatosEquipo;
    private javax.swing.JPanel DatosGenereales;
    public static javax.swing.JTextField Direccion;
    private javax.swing.JButton EditarOs;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField EmitidaPor;
    private javax.swing.JLabel Estatus;
    private javax.swing.JButton GuardarOs;
    private javax.swing.JPanel Importe;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Modelo;
    private javax.swing.JRadioButton No;
    public static javax.swing.JTextField Nombre;
    private javax.swing.JButton NuevaOs;
    private javax.swing.JPanel Observaciones;
    private javax.swing.JLabel Pago;
    private javax.swing.JPanel ReporteCliente;
    private com.toedter.calendar.JDateChooser Salida;
    private javax.swing.JButton SeleccionarCliente;
    private javax.swing.JPanel Servicios;
    private javax.swing.JRadioButton Si;
    public static javax.swing.JTextField Telefono;
    private javax.swing.JFormattedTextField Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbPago;
    private javax.swing.JComboBox<String> cbServicios;
    private javax.swing.JComboBox<String> cbTecnico;
    private com.toedter.calendar.JDateChooser ingreso1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableServicios;
    private javax.swing.JTextArea jTxtObservaciones;
    private javax.swing.JTextArea jTxtReporte;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JTextField modelo;
    private javax.swing.JPanel num;
    private javax.swing.JTextField numOS;
    private javax.swing.JTextArea txtAccerosorios;
    // End of variables declaration//GEN-END:variables
}
