/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import clases.conexionS;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import clases.*;
import Pantallas.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author rica_
 */
public class Os extends javax.swing.JInternalFrame {

    Connection conexion = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel tServicios = new DefaultTableModel();
    int suma = 0;

    /**
     * Creates new form Os
     */
    public Os() {
        initComponents();
        Contraseña.setEnabled(false);
        txtAccerosorios.setEnabled(false);
        Actualizar.setEnabled(false);

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        conexion = conexionS.conn();
        txtAccerosorios.setLineWrap(true);
        txtAccerosorios.setWrapStyleWord(true);
        jTxtObservaciones.setLineWrap(true);
        jTxtObservaciones.setWrapStyleWord(true);
        numOS.setEnabled(false);
        agregarnumOS();

        cargarCombobox();

    }

    private void agregarnumOS() {
        String sql = "Select count(*) from os";

        Statement leer;
        try {
            leer = conexion.createStatement();
            rs = leer.executeQuery(sql);

            if (rs.next()) {
                int aux = Integer.parseInt(rs.getString(1));

                aux += 1;

                if (aux <= 9) {
                    numOS.setText("A00" + aux);
                } else if (aux >= 10 && aux <= 99) {
                    numOS.setText("A0" + aux);
                } else if (aux >= 100) {
                    numOS.setText("A" + aux);
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Os.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarCombobox() {

        cbTecnicos cb = new cbTecnicos();
        cbTecnico.setModel(cb.getvalues());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NuevaOs = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DatosGenereales = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        numOS = new javax.swing.JTextField();
        EmitidaPor = new javax.swing.JTextField();
        cbTecnico = new javax.swing.JComboBox<>();
        Salida = new com.toedter.calendar.JDateChooser();
        ingreso = new com.toedter.calendar.JDateChooser();
        DatosClientes = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        AgregarCliente = new javax.swing.JButton();
        SeleccionarCliente = new javax.swing.JButton();
        DatosEquipo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        numSerie = new javax.swing.JTextField();
        TipoDispositivo = new javax.swing.JTextField();
        Accesorios = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Si = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAccerosorios = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JTextField();
        Observaciones = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtObservaciones = new javax.swing.JTextArea();
        ReporteCliente = new javax.swing.JPanel();
        reporte = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtReporte = new javax.swing.JTextArea();
        Estatus = new javax.swing.JLabel();
        Pago = new javax.swing.JLabel();
        GuardarOs = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1326, 880));
        setPreferredSize(new java.awt.Dimension(1326, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 770));

        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_bill_32px.png"))); // NOI18N
        jLabel1.setText("Ordenes de Servicio");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);
        Banner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 40));

        NuevaOs.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        NuevaOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_24px_1.png"))); // NOI18N
        NuevaOs.setText("Nuevo");
        NuevaOs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NuevaOs.setPreferredSize(new java.awt.Dimension(75, 23));
        NuevaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaOsActionPerformed(evt);
            }
        });
        Banner.add(NuevaOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_edit_24px.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Banner.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, 40));

        DatosGenereales.setBackground(new java.awt.Color(153, 153, 153));
        DatosGenereales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosGenereales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(80, 34, 34));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATOS GENERALES");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        DatosGenereales.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        label1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label1.setText("N° OS");
        DatosGenereales.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label2.setText("Fecha de ingreso");
        DatosGenereales.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label4.setText("Fecha de entrega");
        DatosGenereales.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        label5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label5.setText("Emitida por");
        DatosGenereales.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label6.setText("Tecnico asignado");
        DatosGenereales.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        numOS.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOSActionPerformed(evt);
            }
        });
        DatosGenereales.add(numOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        EmitidaPor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DatosGenereales.add(EmitidaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, -1));

        cbTecnico.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbTecnico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTecnicoItemStateChanged(evt);
            }
        });
        cbTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTecnicoActionPerformed(evt);
            }
        });
        DatosGenereales.add(cbTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        Salida.setDateFormatString("dd/MM/y");
        Salida.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DatosGenereales.add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        ingreso.setDateFormatString("dd/MM/y");
        ingreso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DatosGenereales.add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        DatosClientes.setBackground(new java.awt.Color(153, 153, 153));
        DatosClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(80, 34, 34));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DATOS DE CLIENTE");
        jPanel21.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        DatosClientes.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel22.setBackground(new java.awt.Color(153, 153, 153));
        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(80, 34, 34));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DATOS DE CLIENTE");
        jPanel23.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        DatosClientes.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 350, 150));

        label7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label7.setText("Correo");
        DatosClientes.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label8.setText("Nombre");
        DatosClientes.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label9.setText("Dirección");
        DatosClientes.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label10.setText("Teléfono");
        DatosClientes.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        DatosClientes.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        Direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        DatosClientes.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, -1));

        Telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        DatosClientes.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, -1));

        Correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        DatosClientes.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, -1));

        AgregarCliente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        AgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_24px_1.png"))); // NOI18N
        AgregarCliente.setText("Agregar");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        DatosClientes.add(AgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        SeleccionarCliente.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        SeleccionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_checklist_24px.png"))); // NOI18N
        SeleccionarCliente.setText("Seleccionar");
        SeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarClienteActionPerformed(evt);
            }
        });
        DatosClientes.add(SeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 30));

        DatosEquipo.setBackground(new java.awt.Color(153, 153, 153));
        DatosEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatosEquipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(80, 34, 34));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATOS DEL EQUIPO");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 30));

        DatosEquipo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        label13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label13.setText("Tipo de Dispositivo");
        DatosEquipo.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label12.setText("Marca");
        DatosEquipo.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label14.setText("Modelo");
        DatosEquipo.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        label11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label11.setText("N° Serie");
        DatosEquipo.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        Marca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DatosEquipo.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 310, -1));

        Modelo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DatosEquipo.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, -1));

        numSerie.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSerieActionPerformed(evt);
            }
        });
        DatosEquipo.add(numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, -1));
        DatosEquipo.add(TipoDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 310, -1));

        Accesorios.setBackground(new java.awt.Color(153, 153, 153));
        Accesorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Accesorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(80, 34, 34));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Accesorios");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 30));

        buttonGroup1.add(Si);
        Si.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        Si.setForeground(new java.awt.Color(255, 255, 255));
        Si.setText("SI");
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        jPanel15.add(Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        buttonGroup1.add(No);
        No.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        No.setForeground(new java.awt.Color(255, 255, 255));
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        jPanel15.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 30));

        Accesorios.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel19.setBackground(new java.awt.Color(153, 153, 153));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(80, 34, 34));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATOS DE CLIENTE");
        jPanel20.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        Accesorios.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 350, 150));

        txtAccerosorios.setColumns(20);
        txtAccerosorios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAccerosorios.setRows(5);
        jScrollPane2.setViewportView(txtAccerosorios);

        Accesorios.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Accesorios");
        Accesorios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        Accesorios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Accesorios.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        Observaciones.setBackground(new java.awt.Color(153, 153, 153));
        Observaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Observaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(80, 34, 34));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OBSERVACIONES");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 30));

        Observaciones.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 30));

        jTxtObservaciones.setColumns(20);
        jTxtObservaciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTxtObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTxtObservaciones);

        Observaciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 890, 110));

        ReporteCliente.setBackground(new java.awt.Color(153, 153, 153));
        ReporteCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ReporteCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reporte.setBackground(new java.awt.Color(80, 34, 34));
        reporte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REPORTE CLIENTE");
        reporte.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 30));

        ReporteCliente.add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jTxtReporte.setColumns(20);
        jTxtReporte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTxtReporte.setRows(5);
        jScrollPane3.setViewportView(jTxtReporte);

        ReporteCliente.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1260, 110));

        Estatus.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Estatus.setForeground(new java.awt.Color(0, 0, 0));
        Estatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estatus.setText("Sin Asignar");
        Estatus.setOpaque(true);
        ReporteCliente.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 110, 30));

        Pago.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Pago.setForeground(new java.awt.Color(0, 0, 0));
        Pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pago.setText("No Pagado");
        Pago.setOpaque(true);
        Pago.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PagoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReporteCliente.add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 120, 30));

        GuardarOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_save_24px.png"))); // NOI18N
        GuardarOs.setText("Guardar");
        GuardarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOsActionPerformed(evt);
            }
        });
        ReporteCliente.add(GuardarOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 480, 30));

        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_update_left_rotation_24px.png"))); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        ReporteCliente.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 480, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DatosGenereales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatosGenereales, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(ReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));

        setBounds(0, 0, 1345, 801);
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void numOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOSActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void cbTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTecnicoActionPerformed

    private void numSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSerieActionPerformed

    private void NuevaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaOsActionPerformed
        // TODO add your handling code here:
        agregarnumOS();
        ingreso.setDate(null);
        Salida.setDate(null);
        EmitidaPor.setText("");
        cbTecnico.setSelectedIndex(0);
        Nombre.setText("");
        Direccion.setText("");
        Telefono.setText("");
        Correo.setText("");
        TipoDispositivo.setText("");
        Marca.setText("");
        Modelo.setText("");
        numSerie.setText("");
        Contraseña.setText("");
        txtAccerosorios.setText("");
        jTxtObservaciones.setText("");
        jTxtReporte.setText("");

        Actualizar.setEnabled(false);
        GuardarOs.setEnabled(true);


    }//GEN-LAST:event_NuevaOsActionPerformed

    private void cbTecnicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTecnicoItemStateChanged
        // TODO add your handling code here:

        if (cbTecnico.getSelectedItem().toString() == "------Selecciona tecnico------") {

            Estatus.setText("Sin Asignar");

        } else {
            Estatus.setText("Asignado");
        }


    }//GEN-LAST:event_cbTecnicoItemStateChanged

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:

        String sql = "Select nombre from clientes where nombre=?";

        try {
            pst = conexion.prepareStatement(sql);
            pst.setString(1, Nombre.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "El cliente "
                        + rs.getString(1) + " Ya esta registrado");
            } else {

                sql = ("insert into clientes(nombre,direccion,telefono,correo)"
                        + "values(?,?,?,?)");
                try {
                    if (Nombre.getText().isEmpty()
                            || Telefono.getText().isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Campos obligatorios vacios");
                    } else {

                        pst = conexion.prepareStatement(sql);
                        pst.setString(1, Nombre.getText());
                        pst.setString(2, Correo.getText());
                        pst.setString(3, Direccion.getText());
                        pst.setString(4, Telefono.getText());
                        pst.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Cliente agregado exitosamente");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void SeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarClienteActionPerformed
        // TODO add your handling code here:

        TableClient tableclient = new TableClient();
        tableclient.setVisible(true);
    }//GEN-LAST:event_SeleccionarClienteActionPerformed

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:

        if (Si.isSelected()) {

            Contraseña.setEnabled(true);
            txtAccerosorios.setEnabled(true);

        }
    }//GEN-LAST:event_SiActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        if (No.isSelected()) {

            Contraseña.setEnabled(false);
            txtAccerosorios.setEnabled(false);

            Contraseña.setText("");
            txtAccerosorios.setText("");

        }
    }//GEN-LAST:event_NoActionPerformed

    private void GuardarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOsActionPerformed
        // TODO add your handling code here:

        String sql = "Select NumOs from os where NumOs=?";

        try {
            pst = conexion.prepareStatement(sql);
            pst.setString(1, numOS.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "La orden Numero:  "
                        + rs.getString(1) + " Ya esta registrado");
            } else {

                sql = ("insert into os (NumOs," //1
                        + "FechaIngreso," //2
                        + "FechaEntrega," //3
                        + "EmitidaPor," //4 
                        + "TecnicoAsignado,"//5
                        + "NombreCliente,"//6
                        + "DireccionCliente,"//7
                        + "TelefonoCliente,"//8
                        + "CorreoCliente,"//9
                        + "TipoDispositivo,"//10
                        + "MarcaDispositivo,"//11
                        + "Modelo,"//12
                        + "NumSerie,"//13
                        + "Contraseña,"//14
                        + "Accesorios,"//15
                        + "Observaciones,"//16
                        + "ReporteCliente,"//17
                        + "Estatus,"
                        + "EstatusPago)"
                        + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

                try {
                    if (numOS.getText().isBlank()
                            || EmitidaPor.getText().isEmpty()
                            || cbTecnico.getSelectedItem().toString()
                            == "------Selecciona tecnico------"
                            || Nombre.getText().isEmpty()
                            || Telefono.getText().isEmpty()
                            || TipoDispositivo.getText().isEmpty()
                            || Marca.getText().isEmpty()
                            || jTxtObservaciones.getText().isEmpty()
                            || jTxtReporte.getText().isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Campos obligatorios"
                                + " vacios, favor de verificar los campos");
                    } else {

                        pst = conexion.prepareStatement(sql);
                        pst.setString(1, numOS.getText());
                        pst.setString(2, ((JTextField) ingreso.getDateEditor().getUiComponent()).getText());
                        pst.setString(3, ((JTextField) Salida.getDateEditor().getUiComponent()).getText());
                        pst.setString(4, EmitidaPor.getText());
                        pst.setString(5, cbTecnico.getSelectedItem().toString());
                        pst.setString(6, Nombre.getText());
                        pst.setString(7, Direccion.getText());
                        pst.setString(8, Telefono.getText());
                        pst.setString(9, Correo.getText());
                        pst.setString(10, TipoDispositivo.getText());
                        pst.setString(11, Marca.getText());
                        pst.setString(12, Modelo.getText());
                        pst.setString(13, numSerie.getText());
                        pst.setString(14, Contraseña.getText());
                        pst.setString(15, txtAccerosorios.getText());
                        pst.setString(16, jTxtObservaciones.getText());
                        pst.setString(17, jTxtReporte.getText());
                        pst.setString(18, Estatus.getText());
                        pst.setString(19, Pago.getText());
                        pst.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Orden de servicio " + numOS.getText() + " Se agrego correctamente");

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_GuardarOsActionPerformed

    private void PagoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PagoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PagoAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TableOS tableos = new TableOS();
        tableos.setVisible(true);
        GuardarOs.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        String sql = ("Update os set "
                + "FechaIngreso=?," //2
                + "FechaEntrega=?," //3
                + "EmitidaPor=?," //4 
                + "TecnicoAsignado=?,"//5
                + "NombreCliente=?,"//6
                + "DireccionCliente=?,"//7
                + "TelefonoCliente=?,"//8
                + "CorreoCliente=?,"//9
                + "TipoDispositivo=?,"//10
                + "MarcaDispositivo=?,"//11
                + "Modelo=?,"//12
                + "NumSerie=?,"//13
                + "Contraseña=?,"//14
                + "Accesorios=?,"//15
                + "Observaciones=?,"//16
                + "ReporteCliente=?,"//17
                + "Estatus=?,"//18
                + "EstatusPago=? where NumOs='" + numOS.getText() + "'");

        try {
            if (numOS.getText().isBlank()
                    || EmitidaPor.getText().isEmpty()
                    || cbTecnico.getSelectedItem().toString()
                    == "------Selecciona tecnico------"
                    || Nombre.getText().isEmpty()
                    || Direccion.getText().isEmpty()
                    || Telefono.getText().isEmpty()
                    || Correo.getText().isEmpty()
                    || TipoDispositivo.getText().isEmpty()
                    || Marca.getText().isEmpty()
                    || jTxtObservaciones.getText().isEmpty()
                    || jTxtReporte.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Campos obligatorios"
                        + " vacios, favor de verificar los campos");
            } else {

                pst = conexion.prepareStatement(sql);
                pst.setString(1, ((JTextField) ingreso.getDateEditor().getUiComponent()).getText());
                pst.setString(2, ((JTextField) Salida.getDateEditor().getUiComponent()).getText());
                pst.setString(3, EmitidaPor.getText());
                pst.setString(4, cbTecnico.getSelectedItem().toString());
                pst.setString(5, Nombre.getText());
                pst.setString(6, Direccion.getText());
                pst.setString(7, Telefono.getText());
                pst.setString(8, Correo.getText());
                pst.setString(9, TipoDispositivo.getText());
                pst.setString(10, Marca.getText());
                pst.setString(11, Modelo.getText());
                pst.setString(12, numSerie.getText());
                pst.setString(13, Contraseña.getText());
                pst.setString(14, txtAccerosorios.getText());
                pst.setString(15, jTxtObservaciones.getText());
                pst.setString(16, jTxtReporte.getText());
                pst.setString(17, Estatus.getText());
                pst.setString(18, Pago.getText());
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Orden de servicio " + numOS.getText() + " Se Actualizo correctamente");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_ActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accesorios;
    public static javax.swing.JButton Actualizar;
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JPanel Banner;
    public static javax.swing.JTextField Contraseña;
    public static javax.swing.JTextField Correo;
    private javax.swing.JPanel DatosClientes;
    private javax.swing.JPanel DatosEquipo;
    private javax.swing.JPanel DatosGenereales;
    public static javax.swing.JTextField Direccion;
    public static javax.swing.JTextField EmitidaPor;
    public static javax.swing.JLabel Estatus;
    private javax.swing.JButton GuardarOs;
    public static javax.swing.JTextField Marca;
    public static javax.swing.JTextField Modelo;
    public static javax.swing.JRadioButton No;
    public static javax.swing.JTextField Nombre;
    private javax.swing.JButton NuevaOs;
    private javax.swing.JPanel Observaciones;
    public static javax.swing.JLabel Pago;
    private javax.swing.JPanel ReporteCliente;
    public static com.toedter.calendar.JDateChooser Salida;
    private javax.swing.JButton SeleccionarCliente;
    public static javax.swing.JRadioButton Si;
    public static javax.swing.JTextField Telefono;
    public static javax.swing.JTextField TipoDispositivo;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cbTecnico;
    public static com.toedter.calendar.JDateChooser ingreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea jTxtObservaciones;
    public static javax.swing.JTextArea jTxtReporte;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    public static javax.swing.JTextField numOS;
    public static javax.swing.JTextField numSerie;
    private javax.swing.JPanel reporte;
    public static javax.swing.JTextArea txtAccerosorios;
    // End of variables declaration//GEN-END:variables
}
